title: Домашняя страница Андрея Малова
email: ndrmlv@ya.ru
description: >-
  Добро пожаловать на домашнюю страницу Андрея Малова (andreymlv)!
baseurl: ""
url: "https://andreymlv.com"
twitter_username: andreymlv
github_username: andreymlv
lang: ru

disqus:
  shortname: andreymlv-com

theme: minima
plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
